"""LangGraph state schema for the RAG workflow."""

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field

from tiny_rag_agent.ingestion.schema import DocumentChunk


class GraphState(BaseModel):
    """Shared state passed through the LangGraph nodes."""

    # Step 1: User input is normalized and stored as the active query.
    query: str = Field(
        ...,
        description="User query text flowing through the graph.",
    )
    # Step 2: Retrieve node fills in candidate chunks for grounding.
    docs: List[DocumentChunk] = Field(
        default_factory=list,
        description="Candidate document chunks retrieved for the query.",
    )
    # Step 3: Grade node scores each chunk (aligned with docs list).
    scores: List[float] = Field(
        default_factory=list,
        description="Relevance scores aligned with docs order.",
    )
    # Step 4: Generate node writes the grounded answer.
    answer: str | None = Field(
        default=None,
        description="Final or intermediate answer generated by the model.",
    )
